extends RefCounted

var request_sequence: int = 100000

func hit(component: CombatComponent, damage: float = 20.0, origin: Vector3 = Vector3(0, 0, -2), kind: StringName = &"light") -> MireTypes.DamageResult:
	request_sequence += 1
	return component.receive_hit(MireTypes.DamageRequest.new(&"fixture_attacker", request_sequence, component.entity_id, damage, kind, origin, &"hostile"))

func fresh(session: Node, component: CombatComponent) -> void:
	session.new_game()
	component.player.input_enabled = true
	component.reset_combat()
	component.player.vitals.reset()

func run(t: SceneTree) -> void:
	var session: Node = t.root.get_node("GameSession")
	session.new_game()
	var actor: MirePlayer = load("res://scenes/player/player.tscn").instantiate()
	t.root.add_child(actor)
	actor.set_physics_process(false)
	var component: CombatComponent = actor.get_node("Combat")
	component.input_driven = false
	component.set_physics_process(false)
	await t.process_frame
	var weapons: Array[Array] = [["rusted_sword", 18.0, 16.0, 0.25, 0.12, 0.43], ["arming_sword", 24.0, 18.0, 0.22, 0.12, 0.38], ["falchion", 29.0, 22.0, 0.30, 0.14, 0.46], ["watchblade", 26.0, 17.0, 0.21, 0.12, 0.32]]
	for weapon: Array in weapons:
		fresh(session, component)
		session.state.inventory[0].item_id = weapon[0]
		var started: MireTypes.ActionResult = component.request_attack(&"light")
		t.check(started.ok and component.phase == &"WINDUP" and session.state.player.stamina == 100.0 - weapon[2], "R12 %s commits one exact light cost" % weapon[0])
		component.advance(weapon[3] - 0.001)
		t.check(component.phase == &"WINDUP", "R12 %s cannot enter active early" % weapon[0])
		component.advance(0.001)
		t.check(component.phase == &"ACTIVE", "R12 %s windup reaches configured boundary" % weapon[0])
		component.advance(weapon[4])
		t.check(component.phase == &"RECOVERY", "R12 %s active duration is configured" % weapon[0])
		component.advance(weapon[5])
		t.check(component.phase == &"IDLE" and session.state.player.stamina == 100.0 - weapon[2] and not session.action_locked, "R12 %s recovery finishes without duplicate cost or regen" % weapon[0])
		fresh(session, component)
		session.state.inventory[0].item_id = weapon[0]
		component.request_attack(&"heavy")
		t.check(session.state.player.stamina == 100 - ceili(weapon[2] * 1.8) and is_equal_approx(component.attack_profile.damage, weapon[1] * 1.6), "R12/R16 %s heavy multipliers apply at creation once" % weapon[0])
		component.advance(0.6)
		t.check(component.phase == &"ACTIVE", "R12 %s heavy windup is 0.60 seconds" % weapon[0])
		component.advance(0.16)
		t.check(component.phase == &"RECOVERY", "R12 %s heavy active is 0.16 seconds" % weapon[0])
		component.advance(0.64)
		t.check(component.phase == &"IDLE", "R12 %s heavy recovery is 0.64 seconds" % weapon[0])
	fresh(session, component)
	session.state.player.stamina = 15.0
	var refused: MireTypes.ActionResult = component.request_attack(&"light")
	t.check(not refused.ok and refused.code == &"insufficient_stamina" and component.phase == &"IDLE" and session.state.player.stamina == 15.0 and not session.action_locked, "R12 insufficient stamina changes no combat state")
	fresh(session, component)
	component.request_attack(&"light")
	component.set_guard(true)
	t.check(not component.guard_held and component.phase == &"WINDUP" and session.action_locked, "R12 guard cannot cancel committed attack and healing/equip lock remains")
	component.advance(0.25 + 0.12 + 0.30)
	t.check(not component.request_attack(&"light").ok, "R12 follow-up outside last 0.12 seconds is rejected")
	component.advance(0.01)
	t.check(component.request_attack(&"light").ok and not component.request_attack(&"light").ok, "R12 exactly one follow-up can be buffered at boundary")
	var first_sequence: int = component.attack_sequence
	component.advance(0.12)
	t.check(component.phase == &"WINDUP" and component.attack_sequence > first_sequence and session.state.player.stamina == 68.0, "R12 buffered attack pays once when started")
	component.advance(0.8)
	t.check(component.phase == &"IDLE" and session.state.player.stamina == 68.0, "R12 fast input cannot queue a third attack")
	fresh(session, component)
	component.request_attack(&"heavy")
	component.advance(0.6 + 0.16 + 0.53)
	t.check(not component.request_attack(&"light").ok, "R12 heavy attack does not accept light combo buffer")
	fresh(session, component)
	session.action_locked = true
	t.check(not component.request_attack(&"light").ok and session.state.player.stamina == 100.0, "R12 healing or other committed action blocks attack")
	for advance_by: float in [0.10, 0.28, 0.50]:
		fresh(session, component)
		component.request_attack(&"light")
		component.advance(advance_by)
		var old_phase: StringName = component.phase
		var old_elapsed: float = component.phase_elapsed
		var old_sequence: int = component.attack_sequence
		t.paused = true
		component.clear_input_edges()
		component.advance(10.0)
		t.paused = false
		t.check(component.phase == old_phase and component.phase_elapsed == old_elapsed and component.attack_sequence == old_sequence and session.state.player.stamina == 84.0 and session.action_locked, "R12 modal freezes %s without clearing committed cost" % old_phase)
	fresh(session, component)
	component.set_guard(true)
	component.advance(0.18)
	var parry: MireTypes.DamageResult = hit(component)
	t.check(parry.outcome == &"parried" and parry.health_damage == 0 and parry.stamina_damage == 5 and is_equal_approx(parry.stagger_seconds, 0.65) and session.state.player.health == 100.0, "R15 parry at exact 0.18 boundary costs five and no health")
	fresh(session, component)
	component.set_guard(true)
	component.advance(0.1801)
	var ordinary: MireTypes.DamageResult = hit(component)
	t.check(ordinary.outcome == &"blocked" and ordinary.stamina_damage == 16 and ordinary.health_damage == 2, "R14/R15 outside parry window uses 20-damage ordinary block")
	fresh(session, component)
	component.set_guard(true)
	component.advance(0.1)
	component.set_guard(false)
	component.set_guard(true)
	t.check(hit(component).outcome == &"blocked", "R15 rapid guard toggle does not reopen parry window")
	component.set_guard(false)
	component.advance(0.55)
	component.set_guard(true)
	t.check(hit(component).outcome == &"parried", "R15 guard becomes parry eligible at 0.65 cooldown boundary")
	fresh(session, component)
	component.set_guard(true)
	component.advance(0.7)
	t.check(hit(component).outcome == &"blocked", "R15 holding guard never reopens its window")
	fresh(session, component)
	session.state.player.stamina = 4.0
	component.set_guard(true)
	var broken: MireTypes.DamageResult = hit(component)
	t.check(broken.outcome == &"guard_broken" and session.state.player.stamina == 0.0 and broken.health_damage == 10 and component.phase == &"STAGGER", "R15 insufficient five stamina cannot parry and guard breaks")
	component.advance(0.899)
	component.set_guard(true)
	t.check(not component.guard_held and not component.request_attack(&"light").ok, "R15 guard break disables attack and guard through 0.899 seconds")
	component.advance(0.001)
	component.set_guard(true)
	t.check(component.guard_held and component.phase == &"IDLE" and not session.action_locked, "R15 guard break unlocks at 0.9 seconds")
	for degrees: float in [-60.0, 60.0, -60.1, 60.1, 180.0]:
		fresh(session, component)
		component.set_guard(true)
		component.advance(0.2)
		var direction := Vector3.FORWARD.rotated(Vector3.UP, deg_to_rad(degrees)) * 2.0 + Vector3.UP * 50.0
		var result: MireTypes.DamageResult = hit(component, 20.0, direction)
		t.check(result.outcome == (&"blocked" if absf(degrees) <= 60.0 else &"hit"), "R14 horizontal frontal cone at %.1f degrees ignores pitch" % degrees)
	fresh(session, component)
	component.set_guard(true)
	t.check(hit(component, 20.0, Vector3(0, 0, 2)).outcome == &"hit", "R15 rear attack cannot be parried in an otherwise legal window")
	for armor_case: Array in [["patched_coat", 20], ["leather_jack", 18], ["mail_coat", 15]]:
		fresh(session, component)
		session.state.inventory[2].item_id = armor_case[0]
		t.check(hit(component).health_damage == armor_case[1], "R16 %s reduction affects actual received health damage" % armor_case[0])
	fresh(session, component)
	session.state.inventory[1].item_id = "kite_shield"
	component.set_guard(true)
	component.advance(0.2)
	t.check(hit(component).stamina_damage == 12, "R14 equipped kite shield changes actual guard cost")
	fresh(session, component)
	var first: MireTypes.DamageResult = hit(component, 10)
	component.advance(0.1)
	var rejected: MireTypes.DamageResult = hit(component, 10)
	component.advance(0.1)
	var next: MireTypes.DamageResult = hit(component, 10)
	t.check(first.health_damage == 10 and rejected.outcome == &"ignored" and next.health_damage == 10 and session.state.player.health == 80.0, "R16 rejected damage never extends player 0.20-second immunity")
	fresh(session, component)
	request_sequence += 1
	var duplicate := MireTypes.DamageRequest.new(&"fixture_attacker", request_sequence, &"player", 10, &"light", Vector3.FORWARD, &"hostile")
	component.receive_hit(duplicate)
	component.advance(0.3)
	t.check(component.receive_hit(duplicate).outcome == &"ignored" and session.state.player.health == 90.0, "R13 received attack sequence cannot deal damage twice after immunity expires")
	fresh(session, component)
	t.check(hit(component, 0.01).health_damage == 1, "R16 non-parry damage has minimum one health loss")
	fresh(session, component)
	var deaths: Array[StringName] = []
	component.died.connect(func(id: StringName) -> void: deaths.append(id))
	var lethal: MireTypes.DamageResult = hit(component, 1000)
	var again: MireTypes.DamageResult = hit(component, 1000)
	t.check(lethal.outcome == &"killed" and again.outcome == &"ignored" and deaths == [&"player"] and session.state.player.health == 0.0, "R16 simultaneous lethal requests emit exactly one stable-ID death")
	fresh(session, component)
	t.check(component.receive_hit(MireTypes.DamageRequest.new(&"player", 1, &"player", 20)).outcome == &"ignored", "R13 self damage is refused")
	t.check(component.receive_hit(MireTypes.DamageRequest.new(&"friend", 1, &"player", 20, &"light", Vector3.FORWARD, &"neutral")).outcome == &"ignored", "R13 neutral damage is refused")
	var enemy_actor := Node3D.new()
	t.root.add_child(enemy_actor)
	var enemy := CombatComponent.new()
	enemy_actor.add_child(enemy)
	enemy.configure_enemy(enemy_actor, &"raider", t.root.get_node("ContentDB").get_enemy(&"deserter_raider"))
	enemy.set_physics_process(false)
	enemy.set_guard(true)
	var enemy_block := enemy.receive_hit(MireTypes.DamageRequest.new(&"player", 500000, &"raider", 20, &"heavy", Vector3.FORWARD, &"player"))
	t.check(enemy_block.outcome == &"blocked" and enemy_block.stamina_damage == 24 and enemy.get_stamina() == 16.0, "R14/R15 enemy has ordinary block only with heavy guard damage multiplier")
	enemy.advance(1.0)
	t.check(enemy.get_stamina() == 16.0, "R15 enemy guard stamina does not regenerate while guarding")
	enemy.set_guard(false)
	enemy.advance(1.0)
	t.check(enemy.get_stamina() == 26.0, "R15 enemy component owns exactly ten stamina per second recovery")
	t.check(not enemy.set_attack_profile(&"thrust", {"damage": 1}).ok, "R12 incomplete boss attack profile is rejected")
	t.check(enemy.set_attack_profile(&"thrust", {"damage": 24, "windup": 0.75, "active": 0.15, "recovery": 0.85, "reach": 2.5, "arc_degrees": 10}).ok and enemy.request_attack(&"thrust").ok, "R12 custom boss profile uses shared commitment API")
	enemy.advance(0.75)
	t.check(enemy.phase == &"ACTIVE", "R12 custom boss attack obeys its windup")
	enemy.apply_stagger(0.65)
	t.check(enemy.phase == &"STAGGER" and not enemy.request_attack(&"light").ok, "R15 parry interruption stops attack through shared stagger API")
	enemy.advance(0.65)
	t.check(enemy.phase == &"IDLE", "R15 parry stagger expires at 0.65 seconds")
	actor.queue_free()
	enemy_actor.queue_free()
	await t.process_frame
